# Generated by Django 5.2.7 on 2025-10-25 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("blog", "0003_alter_article_article_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50, verbose_name="نام کامل")),
                ("comment_text", models.TextField(verbose_name="متن کامنت")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.article",
                        verbose_name="مقاله",
                    ),
                ),
                (
                    "commenting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت مقاله",
                "verbose_name_plural": "کامنت های مقالات",
            },
        ),
    ]
