# Generated by Django 5.2.7 on 2025-10-22 14:17

import apps.blog.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_title",
                    models.CharField(max_length=100, verbose_name="عنوان دسته"),
                ),
                (
                    "summary_description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
            ],
            options={
                "verbose_name": "دسته بندی مقاله",
                "verbose_name_plural": "دسته بندی مقاله ها",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_title",
                    models.CharField(max_length=100, verbose_name="عنوان مقاله"),
                ),
                (
                    "article_text",
                    models.TextField(blank=True, null=True, verbose_name="متن ماقله"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=500, null=True
                    ),
                ),
                (
                    "image_name",
                    models.ImageField(
                        upload_to=apps.blog.models.upload_image_article,
                        verbose_name="عکس مقاله",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقاله ها",
            },
        ),
    ]
