# Generated by Django 5.2.7 on 2025-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_author_alter_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_text",
            field=models.TextField(blank=True, null=True, verbose_name="متن مقاله"),
        ),
    ]
